---
layout: basic
title: Getting Started – Installing and Configuring DeltaSpike
---
:toc:
toc::[]

== Installing and Configuring DeltaSpike
In order to install DeltaSpike, you need to have the following:

== System Requirements
* Latest versions of Java EE or Java SE

* Arquillian CDI container

* Apache OpenWebBeans (OWB) or JBoss Weld reference implementations

* Working internet connection

== Using DeltaSpike with Maven

VERIFY

Download the full DeltaSpike distribution ZIP file from https://deltaspike.apache.org/download.html and extract it.

On the command line, navigate to the DeltaSpike directory and type this command:

----
mvn clean install
----

Maven downloads the DeltaSpike settings from Maven Central and resolves the dependencies.

In a text editor, open the Maven settings.xml and scroll down to the list of URLs. Replace the placeholder <url> text with the path to the DeltaSpike directory. Save the file and exit. 

== Using DeltaSpike without Maven

VERIFY

Download the full DeltaSpike distribution ZIP file from https://deltaspike.apache.org/download.html and extract it. The DeltaSpike JAR files must be added to the source code of a CDI project.

For WAR projects, copy the JAR files into the WEB-INF/lib directory of the project. 

For EAR projects, copy the JAR files into the EAR/lib directory of the project. Add this code to the META-INF/application.xml file:

----
<library-directory>lib</library-directory>
----

== Adding a Server or Servlet Container CDI Implementation
NEED INFO
