---
layout: basic
title: Getting Started – Adding DeltaSpike to Maven Projects
---
:toc:
toc::[]

== Adding DeltaSpike to Maven Projects

=== Configuring the Project pom.xml
To add DeltaSpike capabilities to a project, you must declare it in the pom.xml file of the project.

In a text editor, open the pom.xml file of your project.

Add this code to the list of properties, replacing deltaspike.version with your version of DeltaSpike:

----
<properties>
    <deltaspike.version>1.0.1</deltaspike.version>
</properties>
----

Alternatively, to use the latest DeltaSpike snapshot, add this code to the list of properties:

----
<properties>
    <deltaspike.version>1.0.2-SNAPSHOT</deltaspike.version>
</properties>
----

=== Adding the Core Module Dependency
In a text editor, open the pom.xml file of your project.

To add the core module of DeltaSpike, add this code to the list of dependencies:

----
<dependency>
    <groupId>org.apache.deltaspike.core</groupId>
    <artifactId>deltaspike-core-api</artifactId>
    <version>${deltaspike.version}</version>
    <scope>compile</scope>
</dependency>

<dependency>
    <groupId>org.apache.deltaspike.core</groupId>
    <artifactId>deltaspike-core-impl</artifactId>
    <version>${deltaspike.version}</version>
    <scope>runtime</scope>
</dependency>
----


On the command line, navigate to the directory containing the pom.xml file. Type this command to download the new dependencies to the Maven repository:

----
mvn clean install
----

=== Adding the Option Module Dependencies
In a text editor, open the pom.xml file of your project.

To add the security module, add this code to the list of dependencies:

----
<dependency>
    <groupId>org.apache.deltaspike.modules</groupId>
    <artifactId>deltaspike-security-module-api</artifactId>
    <version>${deltaspike.version}</version>
    <scope>compile</scope>
</dependency>

<dependency>
    <groupId>org.apache.deltaspike.modules</groupId>
    <artifactId>deltaspike-security-module-impl</artifactId>
    <version>${deltaspike.version}</version>
    <scope>runtime</scope>
</dependency>
----

To add the JPA module, add this code to the list of dependencies:

----
<dependency>
    <groupId>org.apache.deltaspike.modules</groupId>
    <artifactId>deltaspike-jpa-module-api</artifactId>
    <version>${deltaspike.version}</version>
    <scope>compile</scope>
</dependency>

<dependency>
    <groupId>org.apache.deltaspike.modules</groupId>
    <artifactId>deltaspike-jpa-module-impl</artifactId>
    <version>${deltaspike.version}</version>
    <scope>runtime</scope>
</dependency>
----

To add the JSF module, add this code to the list of dependencies:

----
<dependency>
    <groupId>org.apache.deltaspike.modules</groupId>
    <artifactId>deltaspike-jsf-module-api</artifactId>
    <version>${deltaspike.version}</version>
    <scope>compile</scope>
</dependency>

<dependency>
    <groupId>org.apache.deltaspike.modules</groupId>
    <artifactId>deltaspike-jsf-module-impl</artifactId>
    <version>${deltaspike.version}</version>
    <scope>runtime</scope>
</dependency>
----

Alternatively, if you do not wish to see log entries during start up or when a deployment fails, use the impl-module. This is recommended for Java EE servers that cannot handle optional classes. To add the impl-module, add this code to the list of dependencies:

----
<dependency>
    <groupId>org.apache.deltaspike.modules</groupId>
    <artifactId>deltaspike-jsf-module-impl-ee6</artifactId>
    <version>${deltaspike.version}</version>
    <scope>runtime</scope>
</dependency>
----

To add the bean validation module, add this code to the list of dependencies:

----
<dependency>
    <groupId>org.apache.deltaspike.modules</groupId>
    <artifactId>deltaspike-bean-validation-module-impl</artifactId>
    <version>${deltaspike.version}</version>
    <scope>runtime</scope>
</dependency>
----

To add the servlet module, add this code to the list of dependencies:

----
<dependency>
    <groupId>org.apache.deltaspike.modules</groupId>
    <artifactId>deltaspike-servlet-module-api</artifactId>
    <version>${deltaspike.version}</version>
    <scope>compile</scope>
</dependency>

<dependency>
    <groupId>org.apache.deltaspike.modules</groupId>
    <artifactId>deltaspike-servlet-module-impl</artifactId>
    <version>${deltaspike.version}</version>
    <scope>runtime</scope>
</dependency>
----

To add the data module, add this code to the list of dependencies:

----
<dependency>
    <groupId>org.apache.deltaspike.modules</groupId>
    <artifactId>deltaspike-data-module-api</artifactId>
    <version>${deltaspike.version}</version>
    <scope>compile</scope>
</dependency>

<dependency>
    <groupId>org.apache.deltaspike.modules</groupId>
    <artifactId>deltaspike-data-module-impl</artifactId>
    <version>${deltaspike.version}</version>
    <scope>runtime</scope>
</dependency>
----

To add the test-control module, add this code to the list of dependencies:

----
<dependency>
    <groupId>org.apache.deltaspike.modules</groupId>
    <artifactId>deltaspike-test-control-module-api</artifactId>
    <version>${deltaspike.version}</version>
    <scope>compile</scope>
</dependency>

<dependency>
    <groupId>org.apache.deltaspike.modules</groupId>
    <artifactId>deltaspike-test-control-module-impl</artifactId>
    <version>${deltaspike.version}</version>
    <scope>runtime</scope>
</dependency>
----

To add the scheduler module, add this code to the list of dependencies:

----
<dependency>
    <groupId>org.apache.deltaspike.modules</groupId>
    <artifactId>deltaspike-scheduler-module-api</artifactId>
    <version>${deltaspike.version}</version>
    <scope>compile</scope>
</dependency>

<dependency>
    <groupId>org.apache.deltaspike.modules</groupId>
    <artifactId>deltaspike-scheduler-module-impl</artifactId>
    <version>${deltaspike.version}</version>
    <scope>runtime</scope>
</dependency>
----

On the command line, navigate to the directory containing the pom.xml file. Type this command to download the new dependencies to the Maven repository:

----
mvn clean install
----

=== Testing Snapshots
To test Snapshot, open the Maven settings.xml file and add the Apache Snapshot-Repository to the list of repositories:

----
<repositories>
    <repository>
        <id>apache-snapshot-repository</id>
        <url>http://repository.apache.org/snapshots/</url>
        <releases>
            <enabled>false</enabled>
        </releases>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>
----

== Configuring Further when Using Java SE
When using DeltaSpike with Java SE, additional JAR files must be provided. These files correspond to the DeltaSpike CDI Controller API. The Controller uses Java Services to resolve the CDI container.

=== Adding the Container Control Module and CDI Container Dependencies

To use DeltaSpike with Java SE, a CDI container must be configured. In a text editor, open the pom.xml file of your project and add this code to the list of properties:

----
<properties>
    <deltaspike.version>1.0.0</deltaspike.version>
    <owb.version>1.2.0</owb.version>
    <weld.version>1.1.9.Final</weld.version>
</properties>
----

To add the DeltaSpike container control API, add this code to the list of dependencies:

----
<dependency>
    <groupId>org.apache.deltaspike.cdictrl</groupId>
    <artifactId>deltaspike-cdictrl-api</artifactId>
    <version>${deltaspike.version}</version>
    <scope>compile</scope>
</dependency>
----

To add the Apache OpenWebBeans container, add this code to the list of dependencies:

----
<dependency>
    <groupId>org.apache.openwebbeans</groupId>
    <artifactId>openwebbeans-impl</artifactId>
    <version>${owb.version}</version>
    <scope>runtime</scope>
</dependency>

<dependency>
    <groupId>org.apache.openwebbeans</groupId>
    <artifactId>openwebbeans-spi</artifactId>
    <version>${owb.version}</version>
    <scope>compile</scope>
</dependency>

<dependency>
    <groupId>org.apache.deltaspike.cdictrl</groupId>
    <artifactId>deltaspike-cdictrl-owb</artifactId>
    <version>${deltaspike.version}</version>
    <scope>runtime</scope>
</dependency>
----

On the command line, navigate to the project directory and type this command to build the Apache OpenWebBeans container:
----
mvn clean install -POWB
----


To add JBoss Weld container, add this code to the list of dependencies:

----
<dependency>
    <groupId>org.apache.deltaspike.cdictrl</groupId>
    <artifactId>deltaspike-cdictrl-weld</artifactId>
    <version>${deltaspike.version}</version>
    <scope>runtime</scope>
</dependency>

<dependency>
    <groupId>org.jboss.weld.se</groupId>
    <artifactId>weld-se</artifactId>
    <version>${weld.version}</version>
    <scope>runtime</scope>
</dependency>
----

On the command line, navigate to the project directory and type this command to build the JBoss Weld reference implementation:
----
mvn clean install -PWeld
----

To add an embedded servlet runtime, add this code to the list of dependencies:

----
<dependency>
    <groupId>org.apache.deltaspike.cdictrl</groupId>
    <artifactId>deltaspike-cdictrl-servlet</artifactId>
    <version>${deltaspike.version}</version>
    <scope>compile</scope>
</dependency>
----

Save the pom.xml file and exit.

On the command line, navigate to the directory containing the pom.xml file. Enter this command to download the new dependencies to the Maven repository:
----
mvn clean install
----

=== Starting a CDI Container

NEED INFO: How does the user call these methods?

A CDI container is started by using DeltaSpike with Java SE. This provides a basis for defining the CDI scope and resolving the injected beans. 

To bootstrap a CDI container in a Java application, the CdiContainer must be instantiated:

NEED INFO: How is the CdiContainer instantiated? 

Once this is completed, call the #boot method to scan CDI-enabled archives for beans and extensions:

NEED INFO: How is this method invoked?

----
import org.apache.deltaspike.cdise.api.CdiContainer;
import org.apache.deltaspike.cdise.api.CdiContainerLoader;

public class MainApp {
    public static void main(String[] args) {

        CdiContainer cdiContainer = CdiContainerLoader.getCdiContainer();
        cdiContainer.boot();

        // You can use CDI here

        cdiContainer.shutdown();
    }
}
----

After booting the container, a start method must be invoked. The following method uses the application-context example:

NEED INFO: How is this method invoked?

----
import org.apache.deltaspike.cdise.api.CdiContainer;
import org.apache.deltaspike.cdise.api.CdiContainerLoader;
import org.apache.deltaspike.cdise.api.ContextControl;
import javax.enterprise.context.ApplicationScoped;

public class MainApp {
    public static void main(String[] args) {

        CdiContainer cdiContainer = CdiContainerLoader.getCdiContainer();
        cdiContainer.boot();

        // Starting the application-context allows to use @ApplicationScoped beans
        ContextControl contextControl = cdiContainer.getContextControl();
        contextControl.startContext(ApplicationScoped.class);

        // You can use CDI here

        cdiContainer.shutdown();
    }
}
----

DeltaSpike uses the BeanProvider implementation to resolve beans. The following method demonstrates how to resolve a bean without qualifiers:

NEED INFO: How is this method invoked?
 
----
EchoService echoService = BeanProvider.getContextualReference(EchoService.class, false);
----

Where EchoService is an interface, the corresponding implementation is resolved. The resolved CDI bean may be used for all CDI concepts, such as the @Inject class. 

To remove all beans from the application, call the #shutdown method.

NEED INFO: How is this method invoked?

== Using DeltaSpike Features
To learn more about the features of DeltaSpike, see the individual module pages and the examples and tutorials pages:

Individual Module Pages

