---
layout: basic
title: Getting Started – DeltaSpike Examples
---
:toc:
toc::[]

== Examples
There are a number of examples available that demonstrate DeltaSpike capabilities. These come packaged with the distribution-full-version.zip file which can be downloaded from https://deltaspike.apache.org/download.html. Each example showcases a different DeltaSpike feature and explores the mechanics of CDI implementation. Users can observe these examples to view DeltaSpike in action and learn how to inject these capabilities into other projects.

=== jse-examples

NEED INFO 

What is the example? (e.g., Java SE extension, demonstrates ... feature, etc.)

What is the purpose of the example? (e.g., showcases integration of JavaSE with DeltaSpike, adds ... to a project, etc.)

When would a person use this example? (e.g., to view JavaSE, add ... functionality, etc.)

Where can the user get the example from? (e.g., GitHub link, filepath, etc.)

=== jsf-examples

NEED INFO

What is the example? (e.g., Java extension, demonstrates ... feature, etc.)

What is the purpose of the example? (e.g., showcases integration of Java with DeltaSpike, adds ... to a project, etc.)

When would a person use this example? (e.g., to view JavaSE, add ... functionality, etc.)

Where can the user get the example from? (e.g., GitHub link, filepath, etc.)

=== jsf-playground

NEED INFO

What is the example? (e.g., Java extension, demonstrates ... feature, etc.)

What is the purpose of the example? (e.g., showcases integration of JavaSE with DeltaSpike, adds ... to a project, etc.)

When would a person use this example? (e.g., to view Java, add ... functionality, etc.)

Where can the user get the example from? (e.g., GitHub link, filepath, etc.)


== Project Templates

NEED INFO

Paragraph about each template:

=== Java SE + CDI + DS
What is the template? (e.g., Java SE extension, demonstrates ... feature, etc.)

What is the purpose of the template? (e.g., showcases integration of JavaSE with DeltaSpike, adds ... to a project, etc.)

When would a person use this template? (e.g., to view JavaSE, add ... functionality, etc.)

Where can the user get the template from? (e.g., GitHub link, filepath, etc.) https://github.com/os890/javase-cdi-ds-project-template


=== JSF + CDI + DS (Servlet-Container)

What is the template? (e.g., JSF servlet container, which demonstrates ..., etc.)

What is the purpose of the template? (e.g., showcases integration of JavaSE with DeltaSpike, adds ... to a project, etc.)

When would a person use this template? (e.g., to view JavaSE, add ... functionality, etc.)

Where can the user get the template from? (e.g., GitHub link, filepath, etc.) https://github.com/os890/javaweb-cdi-ds-project-template


=== EJB + CDI + DS (Module)

What is the template? (e.g., Module type, which demonstrates ..., etc.)

What is the purpose of the template? (e.g., showcases ... module, adds ... to a project, etc.)

When would a person use this template? (e.g., to add ... extension, view ... functionality, etc.)

Where can the user get the template from? (e.g., GitHub link, filepath, etc.) https://github.com/os890/javaee_cdi_ejb_ds_project_template


=== JSF + EJB + CDI + DS (EE-Server)

What is the template? (e.g., server implementation, which uses ..., etc.)

What is the purpose of the template? (e.g., showcases ... module, adds ... to a project, etc.)

When would a person use this template? (e.g., to add ... capabilities, view ... functionality, etc.)

Where can the user get the template from? (e.g., GitHub link, filepath, etc.) https://github.com/os890/javaee_jsf_cdi_ejb_ds_project_template
